# DFS 数据集配置（SHS27k）
dataset:
  name: "shs27k"
  train_file: "data/shs27k_llapa/processed/dfs_train.tsv"
  val_file: "data/shs27k_llapa/processed/dfs_val.tsv"
  test_file: "data/shs27k_llapa/processed/dfs_test.tsv"
  protein_info_file: "protein_info.csv"
